version: '3.8'

#    user: "${UID}:${GID}"
services:
  postgres:
    container_name: postgres
    volumes:
      - database_vol:/var/lib/postgresql
    networks:
      - transc_netw
    ports:
      - 5432:5432
    build: ./postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: "no"


  front_end:
    depends_on:
      - back_end
    container_name: front_end
    volumes:
      - ./front_end/app:/usr/src/app/frontend
#     TODO : Remove previous line and keep next one when project is finished
#     - html_vol:/usr/src/app/frontend
    networks:
      - transc_netw
    build: ./front_end
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    env_file:
      - .env      
    restart: "no"


  back_end:
    depends_on:
      - postgres
    container_name: back_end
    volumes:
      - html_vol:/usr/src/app/backend
    networks:
      - transc_netw
    ports:
      - 3001:3001
    build: ./back_end
    env_file:
      - .env
    restart: "no"


volumes:
  database_vol:
  html_vol:

networks:
  transc_netw:
    driver: bridge
