version: '3.8'

services:
  postgres:
    container_name: postgres
    volumes:
      - database_vol:/var/lib/postgresql/data
    networks:
      - transc_netw
    ports:
      - ${PORT_POSTGRES}:${PORT_POSTGRES}
    build: ./postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    restart: always


  front_end:
    depends_on:
      - back_end
    container_name: front_end
    volumes:
    - html_vol:/usr/src/app/frontend
    networks:
      - transc_netw
    build: ./front_end
    environment:
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
      - WATCHPACK_POLLING=${WATCHPACK_POLLING}
    ports:
      - ${PORT_FRONT}:${PORT_FRONT}
    restart: always


  back_end:
    depends_on:
      - postgres
    container_name: back_end
    volumes:
      - htm:/usr/src/app/backend
    networks:
      - transc_netw
    ports:
      - ${PORT_BACK}:${PORT_BACK}
      - "5555:5555"
    build: ./back_end
    env_file:
      - .env
    restart: always

volumes:
  database_vol:
  html_vol:
  htm:

networks:
  transc_netw:
    driver: bridge
